// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jowgkwkjomtjpkiihmxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvd2drd2tqb210anBraWlobXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyODI4MDEsImV4cCI6MjA4Nzg1ODgwMX0.f61mV_B-I3vAzo4kj_XATWuADHDhCG6iYEm-b2RPiOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});